package io.vertx.kotlin.ext.sql;

import io.vertx.core.json.JsonArray;
import io.vertx.ext.sql.FetchDirection;
import io.vertx.ext.sql.ResultSetConcurrency;
import io.vertx.ext.sql.ResultSetType;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.ext.sql.TransactionIsolation;
import kotlin.Deprecated;
import kotlin.Metadata;
import kotlin.ReplaceWith;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/* compiled from: SQLOptions.kt */
@Metadata(mv = {1, 1, 15}, bv = {1, 0, 3}, k = 2, d1 = {"��>\n��\n\u0002\u0018\u0002\n��\n\u0002\u0010\u000b\n��\n\u0002\u0018\u0002\n��\n\u0002\u0010\u000e\n��\n\u0002\u0018\u0002\n��\n\u0002\u0010\b\n\u0002\b\u0003\n\u0002\u0018\u0002\n��\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\u001a\u0091\u0001\u0010��\u001a\u00020\u00012\n\b\u0002\u0010\u0002\u001a\u0004\u0018\u00010\u00032\n\b\u0002\u0010\u0004\u001a\u0004\u0018\u00010\u00052\n\b\u0002\u0010\u0006\u001a\u0004\u0018\u00010\u00072\n\b\u0002\u0010\b\u001a\u0004\u0018\u00010\t2\n\b\u0002\u0010\n\u001a\u0004\u0018\u00010\u000b2\n\b\u0002\u0010\f\u001a\u0004\u0018\u00010\u000b2\n\b\u0002\u0010\r\u001a\u0004\u0018\u00010\u00032\n\b\u0002\u0010\u000e\u001a\u0004\u0018\u00010\u000f2\n\b\u0002\u0010\u0010\u001a\u0004\u0018\u00010\u00112\n\b\u0002\u0010\u0012\u001a\u0004\u0018\u00010\u00072\n\b\u0002\u0010\u0013\u001a\u0004\u0018\u00010\u0014H\u0007¢\u0006\u0002\u0010\u0015\u001a\u008f\u0001\u0010\u0016\u001a\u00020\u00012\n\b\u0002\u0010\u0002\u001a\u0004\u0018\u00010\u00032\n\b\u0002\u0010\u0004\u001a\u0004\u0018\u00010\u00052\n\b\u0002\u0010\u0006\u001a\u0004\u0018\u00010\u00072\n\b\u0002\u0010\b\u001a\u0004\u0018\u00010\t2\n\b\u0002\u0010\n\u001a\u0004\u0018\u00010\u000b2\n\b\u0002\u0010\f\u001a\u0004\u0018\u00010\u000b2\n\b\u0002\u0010\r\u001a\u0004\u0018\u00010\u00032\n\b\u0002\u0010\u000e\u001a\u0004\u0018\u00010\u000f2\n\b\u0002\u0010\u0010\u001a\u0004\u0018\u00010\u00112\n\b\u0002\u0010\u0012\u001a\u0004\u0018\u00010\u00072\n\b\u0002\u0010\u0013\u001a\u0004\u0018\u00010\u0014¢\u0006\u0002\u0010\u0015¨\u0006\u0017"}, d2 = {"SQLOptions", "Lio/vertx/ext/sql/SQLOptions;", "autoGeneratedKeys", "", "autoGeneratedKeysIndexes", "Lio/vertx/core/json/JsonArray;", "catalog", "", "fetchDirection", "Lio/vertx/ext/sql/FetchDirection;", "fetchSize", "", "queryTimeout", "readOnly", "resultSetConcurrency", "Lio/vertx/ext/sql/ResultSetConcurrency;", "resultSetType", "Lio/vertx/ext/sql/ResultSetType;", "schema", "transactionIsolation", "Lio/vertx/ext/sql/TransactionIsolation;", "(Ljava/lang/Boolean;Lio/vertx/core/json/JsonArray;Ljava/lang/String;Lio/vertx/ext/sql/FetchDirection;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Boolean;Lio/vertx/ext/sql/ResultSetConcurrency;Lio/vertx/ext/sql/ResultSetType;Ljava/lang/String;Lio/vertx/ext/sql/TransactionIsolation;)Lio/vertx/ext/sql/SQLOptions;", "sqlOptionsOf", "vertx-lang-kotlin"})
/* loaded from: reader.jar:BOOT-INF/lib/vertx-lang-kotlin-3.8.5.jar:io/vertx/kotlin/ext/sql/SQLOptionsKt.class */
public final class SQLOptionsKt {
    @NotNull
    public static /* synthetic */ SQLOptions sqlOptionsOf$default(Boolean bool, JsonArray jsonArray, String str, FetchDirection fetchDirection, Integer num, Integer num2, Boolean bool2, ResultSetConcurrency resultSetConcurrency, ResultSetType resultSetType, String str2, TransactionIsolation transactionIsolation, int i, Object obj) {
        if ((i & 1) != 0) {
            bool = (Boolean) null;
        }
        if ((i & 2) != 0) {
            jsonArray = (JsonArray) null;
        }
        if ((i & 4) != 0) {
            str = (String) null;
        }
        if ((i & 8) != 0) {
            fetchDirection = (FetchDirection) null;
        }
        if ((i & 16) != 0) {
            num = (Integer) null;
        }
        if ((i & 32) != 0) {
            num2 = (Integer) null;
        }
        if ((i & 64) != 0) {
            bool2 = (Boolean) null;
        }
        if ((i & 128) != 0) {
            resultSetConcurrency = (ResultSetConcurrency) null;
        }
        if ((i & 256) != 0) {
            resultSetType = (ResultSetType) null;
        }
        if ((i & 512) != 0) {
            str2 = (String) null;
        }
        if ((i & 1024) != 0) {
            transactionIsolation = (TransactionIsolation) null;
        }
        return sqlOptionsOf(bool, jsonArray, str, fetchDirection, num, num2, bool2, resultSetConcurrency, resultSetType, str2, transactionIsolation);
    }

    @NotNull
    public static final SQLOptions sqlOptionsOf(@Nullable Boolean autoGeneratedKeys, @Nullable JsonArray autoGeneratedKeysIndexes, @Nullable String catalog, @Nullable FetchDirection fetchDirection, @Nullable Integer fetchSize, @Nullable Integer queryTimeout, @Nullable Boolean readOnly, @Nullable ResultSetConcurrency resultSetConcurrency, @Nullable ResultSetType resultSetType, @Nullable String schema, @Nullable TransactionIsolation transactionIsolation) {
        SQLOptions $this$apply = new SQLOptions();
        if (autoGeneratedKeys != null) {
            $this$apply.setAutoGeneratedKeys(autoGeneratedKeys.booleanValue());
        }
        if (autoGeneratedKeysIndexes != null) {
            $this$apply.setAutoGeneratedKeysIndexes(autoGeneratedKeysIndexes);
        }
        if (catalog != null) {
            $this$apply.setCatalog(catalog);
        }
        if (fetchDirection != null) {
            $this$apply.setFetchDirection(fetchDirection);
        }
        if (fetchSize != null) {
            $this$apply.setFetchSize(fetchSize.intValue());
        }
        if (queryTimeout != null) {
            $this$apply.setQueryTimeout(queryTimeout.intValue());
        }
        if (readOnly != null) {
            $this$apply.setReadOnly(readOnly.booleanValue());
        }
        if (resultSetConcurrency != null) {
            $this$apply.setResultSetConcurrency(resultSetConcurrency);
        }
        if (resultSetType != null) {
            $this$apply.setResultSetType(resultSetType);
        }
        if (schema != null) {
            $this$apply.setSchema(schema);
        }
        if (transactionIsolation != null) {
            $this$apply.setTransactionIsolation(transactionIsolation);
        }
        return $this$apply;
    }

    @Deprecated(message = "This function will be removed in a future version", replaceWith = @ReplaceWith(imports = {}, expression = "sqlOptionsOf(autoGeneratedKeys, autoGeneratedKeysIndexes, catalog, fetchDirection, fetchSize, queryTimeout, readOnly, resultSetConcurrency, resultSetType, schema, transactionIsolation)"))
    @NotNull
    public static /* synthetic */ SQLOptions SQLOptions$default(Boolean bool, JsonArray jsonArray, String str, FetchDirection fetchDirection, Integer num, Integer num2, Boolean bool2, ResultSetConcurrency resultSetConcurrency, ResultSetType resultSetType, String str2, TransactionIsolation transactionIsolation, int i, Object obj) {
        if ((i & 1) != 0) {
            bool = (Boolean) null;
        }
        if ((i & 2) != 0) {
            jsonArray = (JsonArray) null;
        }
        if ((i & 4) != 0) {
            str = (String) null;
        }
        if ((i & 8) != 0) {
            fetchDirection = (FetchDirection) null;
        }
        if ((i & 16) != 0) {
            num = (Integer) null;
        }
        if ((i & 32) != 0) {
            num2 = (Integer) null;
        }
        if ((i & 64) != 0) {
            bool2 = (Boolean) null;
        }
        if ((i & 128) != 0) {
            resultSetConcurrency = (ResultSetConcurrency) null;
        }
        if ((i & 256) != 0) {
            resultSetType = (ResultSetType) null;
        }
        if ((i & 512) != 0) {
            str2 = (String) null;
        }
        if ((i & 1024) != 0) {
            transactionIsolation = (TransactionIsolation) null;
        }
        return SQLOptions(bool, jsonArray, str, fetchDirection, num, num2, bool2, resultSetConcurrency, resultSetType, str2, transactionIsolation);
    }

    @Deprecated(message = "This function will be removed in a future version", replaceWith = @ReplaceWith(imports = {}, expression = "sqlOptionsOf(autoGeneratedKeys, autoGeneratedKeysIndexes, catalog, fetchDirection, fetchSize, queryTimeout, readOnly, resultSetConcurrency, resultSetType, schema, transactionIsolation)"))
    @NotNull
    public static final SQLOptions SQLOptions(@Nullable Boolean autoGeneratedKeys, @Nullable JsonArray autoGeneratedKeysIndexes, @Nullable String catalog, @Nullable FetchDirection fetchDirection, @Nullable Integer fetchSize, @Nullable Integer queryTimeout, @Nullable Boolean readOnly, @Nullable ResultSetConcurrency resultSetConcurrency, @Nullable ResultSetType resultSetType, @Nullable String schema, @Nullable TransactionIsolation transactionIsolation) {
        SQLOptions $this$apply = new SQLOptions();
        if (autoGeneratedKeys != null) {
            $this$apply.setAutoGeneratedKeys(autoGeneratedKeys.booleanValue());
        }
        if (autoGeneratedKeysIndexes != null) {
            $this$apply.setAutoGeneratedKeysIndexes(autoGeneratedKeysIndexes);
        }
        if (catalog != null) {
            $this$apply.setCatalog(catalog);
        }
        if (fetchDirection != null) {
            $this$apply.setFetchDirection(fetchDirection);
        }
        if (fetchSize != null) {
            $this$apply.setFetchSize(fetchSize.intValue());
        }
        if (queryTimeout != null) {
            $this$apply.setQueryTimeout(queryTimeout.intValue());
        }
        if (readOnly != null) {
            $this$apply.setReadOnly(readOnly.booleanValue());
        }
        if (resultSetConcurrency != null) {
            $this$apply.setResultSetConcurrency(resultSetConcurrency);
        }
        if (resultSetType != null) {
            $this$apply.setResultSetType(resultSetType);
        }
        if (schema != null) {
            $this$apply.setSchema(schema);
        }
        if (transactionIsolation != null) {
            $this$apply.setTransactionIsolation(transactionIsolation);
        }
        return $this$apply;
    }
}
